ageil/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^gestionEtudiant/', include('etudiantManager.urls')),
	url(r'^gestionEnseignement/', include('enseignementManager.urls')),
	url(r'^gestionJury/', include('juryManager.urls')),
	url(r'^gestionStatistique/', include('statistiqueManager.urls')),
	url(r'^', include('home.urls')),
]

etudiantManager/urls.py
# coding: utf8
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'listeEtudiant', views.home),
	
	url(r'(?P<num>\d+)/modifierEtudiantInfoGestion$', views.modifierEtudiantInfoGestion),
	url(r'(?P<num>\d+)/modifierEtudiantInfoPerso$', views.modifierEtudiantInfoPerso),
	url(r'(?P<num>\d+)/modifierEtudiantInfoBAC$', views.modifierEtudiantInfoBAC),
	
	url(r'(?P<num>\d+)/modifierStatutEtudiant$', views.modifierStatutEtudiant),
	
	url(r'(?P<num>\d+)/ajouterCursusPreDUT$', views.ajouterCursusPreDUT),
	url(r'(?P<num>\d+)/ajouterCursusPostDUT$', views.ajouterCursusPostDUT),
	
	url(r'(?P<idCursus>\d+)/modifierCursusPreDUT$', views.modifierCursusPreDUT),
	url(r'(?P<idCursus>\d+)/modifierCursusPostDUT$', views.modifierCursusPostDUT),
	
	url(r'(?P<idCursus>\d+)/supprimerCursusPreDUT$', views.supprimerCursusPreDUT),
	url(r'(?P<idCursus>\d+)/supprimerCursusPostDUT$', views.supprimerCursusPostDUT),
	
	url(r'(?P<num>\d+)/supprimerEtudiant$', views.supprimerEtudiant),
	
	url(r'(?P<num>\d+)/modifierVersionSemestreActuelEtudiant$', views.modifierVersionSemestreActuelEtudiant),
	url(r'(?P<num>\d+)/modifierModeleFormationDuSemestreAnnualise$', views.modifierModeleFormationDuSemestreAnnualise),
	url(r'(?P<num>\d+)/modifierMoyenne/(?P<idSemestreAnnualise>\d+)$', views.modifierMoyenne),
	
    url(r'(?P<num>\d+)$', views.consulterEtudiant),
	
	url(r'ajouterEtudiantInfoGestion$', views.ajouterEtudiantInfoGestion),
	url(r'ajouterEtudiantInfoPerso$', views.ajouterEtudiantInfoPerso),
	url(r'ajouterEtudiantInfoBAC$', views.ajouterEtudiantInfoBAC),
	
	url(r'ajouterEtudiant$', views.ajouterEtudiant),
	
	url(r'paramImportEtudiant$', views.paramImportEtudiant),
    url(r'importerEtudiant$', views.verifImportEtudiantSemestreUnique),
	
	url(r'paramImportMoyenne$', views.paramImportMoyenne),
    url(r'importerMoyenne$', views.importerMoyenne),
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'travaux$', views.travaux),
    url(r'accueil$', views.home),
    url(r'$', views.home),
]

etudiantManager/models.py
from django.db import models

# Create your models here.

home/models.py
# coding: utf8
from django.db import models

# Create your models here.

"""
Un etudiant et toutes ses infos
numero : unique, propre à chaque étudiant, OBLIGATOIRE
nom, prenom : OBLIGATOIRE
statut : permet de différencier les étudiants "normaux", redoublants ou réorientés
semestreActuel : son semestre actuel (EX: 'S1 2016/2017'), OBLIGATOIRE
sexe, telephone, dateNaissance, adresse, email, informationsSupplementaires : Info variés optionelles
BAC : quel BAC à fait cet étudiant, optionel
mentionBAC : La mention qu'il a obtenu, optionel
anneeBAC : l'AnneeUniversitaire durant laquelle l'étudiant a obtenu son BAC
"""
class Etudiant(models.Model):
	numero = models.IntegerField(verbose_name='Numéro étudiant')
	nom = models.CharField(max_length=50)
	prenom = models.CharField(max_length=50)
	statut = models.ForeignKey('StatutEtudiant')
	
	# permet de savoir dans quel semestre est inscrit l'étudiant
	semestreActuel = models.ForeignKey('SemestreAnnualise', verbose_name='Semestre actuel', null=True, blank=True)
	
	sexe = models.ForeignKey('Sexe', null=True, blank=True)
	telephone = models.CharField(max_length=50, null=True, blank=True)
	dateNaissance = models.DateField(null=True, blank=True, verbose_name='Date de naissance')
	adresse = models.CharField(max_length=200, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	informationsSupplementaires = models.TextField(max_length=500, null=True, blank=True, verbose_name='Informations supplémentaires')
	
	# informations concernant le BAC
	BAC = models.ForeignKey('BAC', verbose_name='BAC', null=True, blank=True)
	mentionBAC = models.ForeignKey('MentionBACPossible', verbose_name='Mention du BAC', null=True, blank=True)
	anneeBAC = models.ForeignKey('AnneeUniversitaire', verbose_name='Année du BAC', null=True, blank=True)
	
	def __str__(self):
		return str(self.numero) + " : " + self.prenom + " " + self.nom

"""
La liste exaustive et fini des sexes : M et F
"""		
class Sexe(models.Model):
	sexe = models.CharField(max_length=1)
	
	def __str__(self):
		return self.sexe


"""
La liste exaustive et fini des statut possible d'un étudiant (normal, redoublant, réorienté, diplomé)
"""
class StatutEtudiant(models.Model):
	statut = models.CharField(max_length=50)
	
	def __str__(self):
		return self.statut

"""
La liste exaustive et fini des semestre d'un DUT : S1, S2, S3, S4
"""
class SemestrePossible(models.Model):
	semestre = models.CharField(max_length=2)
	
	def __str__(self):
		return self.semestre

"""
Les années universitaire : EX: '2016/2017', '2013/2014'
"""
class AnneeUniversitaire(models.Model):
	anneeUniversitaire = models.CharField(max_length=20)
	
	def __str__(self):
		return str(self.anneeUniversitaire)

"""
Les semestres de chaque année et le modèle de formation qui lui est lié : Ex: 'S1 2016/2017'
"""
class SemestreAnnualise(models.Model):
	semestre = models.ForeignKey('SemestrePossible')
	anneeUniversitaire = models.ForeignKey('AnneeUniversitaire')
	modeleFormation = models.ForeignKey('ModeleFormation')
	etatSemestre = models.ForeignKey('EtatSemestrePossible')
	
	def __str__(self):
		return self.semestre.__str__() + " " + self.anneeUniversitaire.__str__()

"""

"""
class EtatSemestrePossible(models.Model):
	etat = models.CharField(max_length=50)
	
	def __str__(self):
		return self.etat

"""
Permet de relier un étudiant à l'ensemble des semestre qu'il a fait
Contrairement à semestreActuel de Etudiant, les ligne de cette table perdurent dans le temps
"""
class Association_Etudiant_SemestreAnnualise(models.Model):
	etudiant = models.ForeignKey('Etudiant')
	semestre = models.ForeignKey('SemestreAnnualise')
	modeleSemestre = models.ForeignKey('ModeleSemestre')
	resultatSemestreCalcule = models.ForeignKey('ResultatSemestrePossible', related_name='resultatSemestreCalcule')
	resultatSemestrePreJury = models.ForeignKey('ResultatSemestrePossible', related_name='resultatSemestrePreJury')
	resultatSemestreJury = models.ForeignKey('ResultatSemestrePossible', related_name='resultatSemestreJury')
	devenirEtudiant = models.ForeignKey('DevenirEtudiantPossible')
	
	def __str__(self):
		return self.etudiant.__str__() + " " + self.semestre.__str__()

"""
Liste exaustive et fini des codes de resultat possible pour un semestre plus l'état 'ATTENTE_DE_DECISION' pour signaler que le résultat n'est pas encore calculé:
	ATTENTE_DE_DECISION, VAL, NATT, NATB, DEF, ADAC, AJPC, VALC
"""
class ResultatSemestrePossible(models.Model):
	codeResultat = models.CharField(max_length=20)
	
	def __str__(self):
		return self.codeResultat

"""
Liste exaustive et fini des codes pour le devenir d'un étudiant plus l'état 'ATTENTE_DE_DECISION' pour signaler que le résultat n'est pas encore calculé:
	ATTENTE_DE_DECISION, Réo, S1, S2, S3, S4, DUT
"""
class DevenirEtudiantPossible(models.Model):
	code = models.CharField(max_length=20)
	
	def __str__(self):
		return self.code
	
"""
Liste des semestre dont on a généré le doc jury mais pas encore cloturés
"""
class SemestreAnnualiseJuryEnCours(models.Model):
	semestreAnnualise = models.ForeignKey('SemestreAnnualise')
	
	def __str__(self):
		return self.semestreAnnualise

"""
Le modèle qui représente la structure de la formation au sein du DUT
nom : unique, permet d'identifier le modèle sur l'interface utilisateur, OBLIGATOIRE
description : optionel
"""
class ModeleFormation(models.Model):
	nom = models.CharField(max_length=100)
	description = models.TextField(max_length=500, null=True, blank=True)
	
	def __str__(self):
		return self.nom

"""
Modèle d'un semestre du DUT
typeSemestre : S1, S2, S3 ou S4, OBLIGATOIRE
intitule : unique, permet d'identifier le modèle sur l'interface utilisateur, OBLIGATOIRE
modeleFormation : le modèle de formation qui comprend ce modèle de semestre, OBLIGATOIRE
"""
class ModeleSemestre(models.Model):
	codeApogee = models.CharField(max_length=100)
	typeSemestre = models.ForeignKey('SemestrePossible')
	intitule = models.CharField(max_length=100)
	modeleFormation = models.ForeignKey('ModeleFormation')
	
	def __str__(self):
		return self.intitule

"""
Modèle d'une UE du DUT
code : le code de l'UE, permet d'importer les moyennes! OBLIGATOIRE
intitule : unique, permet d'identifier le modèle sur l'interface utilisateur, OBLIGATOIRE
coefficient : le coefficient de l'UE
modeleSemestre : le modèle de semestre qui comprend ce modèle d'UE, OBLIGATOIRE
"""
class ModeleUE(models.Model):
	codeApogee = models.CharField(max_length=100)
	code = models.CharField(max_length=100)
	intitule = models.CharField(max_length=100)
	coefficient = models.FloatField()
	modeleSemestre = models.ForeignKey('ModeleSemestre')
	
	def __str__(self):
		return self.intitule

"""
Modèle d'un module du DUT
code : le code du module, permet d'importer les moyennes! OBLIGATOIRE
intitule : unique, permet d'identifier le modèle sur l'interface utilisateur, OBLIGATOIRE
coefficient : le coefficient du module
modeleUE : le modèle d'UE qui comprend ce modèle de module, OBLIGATOIRE
"""
class ModeleModule(models.Model):
	codeApogee = models.CharField(max_length=100)
	code = models.CharField(max_length=100)
	intitule = models.CharField(max_length=100)
	coefficient = models.FloatField()
	modeleUE = models.ForeignKey('ModeleUE')
	
	def __str__(self):
		return self.intitule

"""
La moyenne d'un Etudiant donné pour un ModeleSemestre donné
semestreAnnualise : quand l'Etudiant a t'il obtenu cet moyenne, util pour le cas de redoublement de semestre
"""
class MoyenneSemestre(models.Model):
	moyenne = models.FloatField()
	modeleSemestre = models.ForeignKey('ModeleSemestre')
	etudiant = models.ForeignKey('Etudiant')
	semestreAnnualise = models.ForeignKey('SemestreAnnualise')
	
	def __str__(self):
		return self.semestreAnnualise.__str__() + " " + self.modeleSemestre.__str__() + " " + self.etudiant.__str__() + ' ' + str(self.moyenne)

"""
La moyenne d'un Etudiant donné pour un ModeleUE donné
semestreAnnualise : quand l'Etudiant a t'il obtenu cet moyenne, util pour le cas de redoublement de semestre
"""
class MoyenneUE(models.Model):
	moyenne = models.FloatField()
	modeleUE = models.ForeignKey('ModeleUE')
	etudiant = models.ForeignKey('Etudiant')
	semestreAnnualise = models.ForeignKey('SemestreAnnualise')
	
	def __str__(self):
		return self.semestreAnnualise.__str__() + " " + self.modeleUE.__str__() + " " + self.etudiant.__str__() + ' ' + str(self.moyenne)

"""
La moyenne d'un Etudiant donné pour un ModeleModule donné
semestreAnnualise : quand l'Etudiant a t'il obtenu cet moyenne, util pour le cas de redoublement de semestre
"""
class MoyenneModule(models.Model):
	moyenne = models.FloatField()
	modeleModule = models.ForeignKey('ModeleModule')
	etudiant = models.ForeignKey('Etudiant')
	semestreAnnualise = models.ForeignKey('SemestreAnnualise')
	
	def __str__(self):
		return self.semestreAnnualise.__str__() + " " + self.modeleModule.__str__() + " " + self.etudiant.__str__() + ' ' + str(self.moyenne)

"""
La liste exaustive et fini des type de BAC existant
	Général, Technologique, Professionnel, Autre
"""
class TypeBAC(models.Model):
	typeBAC = models.CharField(max_length=50)

	def __str__(self):
		return self.typeBAC

"""
Liste des BAC existant, modifiable par l'utilisateur
intitule : unique, permet d'identifier le modèle sur l'interface utilisateur, OBLIGATOIRE
typeBAC : de quel type est ce BAC (Général, Technologique, Professionnel ou Autre)
informationsSupplementaires : Info variés optionelles
"""
class BAC(models.Model):
	intitule = models.CharField(max_length=100)
	typeBAC = models.ForeignKey('TypeBAC', verbose_name='Type de BAC')
	informationsSupplementaires = models.TextField(max_length=400, null=True, blank=True, verbose_name='Informations supplémentaires')

	def __str__(self):
		return self.intitule + " (" + self.typeBAC.__str__() + ")"

"""
La liste exaustive et fini des mentions possible au BAC plus 'Non' si pas de mention
	'Non', 'Assez Bien', 'Bien', 'Très Bien'
"""
class MentionBACPossible (models.Model):

etudiantManager/templates/etudiantManager/ajouterCursusPreDUT.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Ajout d'un cursus Pré-DUT à l'étudiant {{etudiant.nom}} {{etudiant.prenom}}</h1>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		
		<p><label for="annee">Année universitaire :</label> <select id="annee" name="annee" required>
			{% for annee in anneesUniversitaires %}
				<option value="{{annee}}">{{annee}}</option>
			{% endfor %}
		</select></p>
		
		{{ form.as_p }}
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/ajouterEtudiantInfoBAC.html
{% extends "base.html" %}
{% load static %}
{% block content %}

	<script src="/static/onglets.js" type="text/javascript" > </script>

	<h1>Ajout d'un nouvel Etudiant (étape 3/3)</h1>
	
	<h2>Informations concernant le BAC :</h2>
	
	<form method='POST' action='/gestionEtudiant/ajouterEtudiant'>
		{% csrf_token %}
		{% for info in infosPOST %}
			<input type="hidden" name="{{info.key}}" value="{{info.value}}">
		{% endfor %}
		
		<p><label for="id_BAC">BAC :</label> <select id="id_BAC" name="BAC">
		<option value="" selected="selected">---------</option>
		{% for BAC in BACs %}
			<option value="{{BAC.id}}">{{BAC}}</option>
		{% endfor %}
		</select></p>
           
		<p><label for="id_mentionBAC">Mention du BAC :</label> <select id="id_mentionBAC" name="mentionBAC">
		<option value="" selected="selected">---------</option>
		{% for mention in mentions %}
			<option value="{{mention.id}}">{{mention}}</option>
		{% endfor %}
		</select></p>
		
		<input type="hidden" value="" name="anneeBAC">
		<p><label for="anneeDuBAC">Année du BAC :</label> <select id="anneeDuBAC" name="anneeDuBAC">
		<option value="" selected="selected">---------</option>
		{% for annee in anneesUniversitaires %}
			<option value="{{annee}}">{{annee}}</option>
		{% endfor %}
		</select></p>
		  
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>


<!-- On ajoute un lien qui permet à l'utilisateur d'ajouter un Bac s'il en existe pas 
    la fonction "popitup" se trouve dans le onglets.js elle permet d'ouvrir une nouvelle fenetre navigateur avec url souhaité-->
    <p>Le BAC souhaité n'est pas disponible : <a href="#" onclick="return popitup('/gestionEnseignement/BAC')" ><input type=button value="Ajouter un BAC"></a>
	<br><i> Penser à recharger la page une fois le BAC ajouté</i>
	</p>
	
{% endblock %}

etudiantManager/templates/etudiantManager/ajouterEtudiantInfoPerso.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Ajout d'un nouvel Etudiant (étape 2/3)</h1>
	
	<h2>Informations personnelles :</h2>
	
	<form method='POST' action='/gestionEtudiant/ajouterEtudiantInfoBAC'>
		{% csrf_token %}
		{% for info in infosPOST %}
			<input type="hidden" name="{{info.key}}" value="{{info.value}}">
		{% endfor %}
		
		{{ form.as_p }}
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/creerSemestreAnnualise.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Vous devez spécifier le modèle de formation à utiliser pour les étudiants du {{semestrePossible}} {{anneeUniversitaire}}</h1>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		
		{% for info in infosPOST %}
			<input type="hidden" name="{{info.key}}" value="{{info.value}}">
		{% endfor %}
		
		<p><label for="id_modeleFormation">Modèle de formation :</label>
		{% if not modelesFormation %}
			 Aucun modèle de formation existant ! <a href="/gestionEnseignement/formation"><input type="button" value="Créer un modèle de formation"></a>
		{% else %}
		<select id="id_modeleFormation" name="modeleFormation" required>
			{% for modele in modelesFormation %}
				<option value="{{modele.id}}">{{modele.nom}}</option>
			{% endfor %}
		</select>
		{% endif %}</p>
		
		<input type="submit" value="Valider"
		{% if not modelesFormation %}
			disabled
			alt="Vous devez d'abord créer un modèle de formation"
			title="Vous devez d'abord créer un modèle de formation"
		{% endif %}
		 >
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/importerMoyenne.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h2>Tableau récapitulatif des moyennes importées :</h2>
	<ul>
	{% for moyenne in listeLigneMoyenne %}
		<li>{{moyenne}}</li>
	{% endfor %}
	</ul>
	<div class="blockScrollable">
		<table class="listeMoyenne">
		<tr>
			{% for entete in premiereLigneTableau %}
				<th>{{entete}}</th>
			{% endfor %}
		</tr>
		{% for ligne in listeLigneTableau %}
			<tr>
				{% for colonne in ligne %}
					<td>{{colonne}}</td>
				{% endfor %}
			</tr>
		{% endfor %}
		</table>
	</div>
	<br>
	<a href='/gestionEtudiant/listeEtudiant'><input type="button" value="Retour à la gestion des étudiants" /></a>
{% endblock %}

etudiantManager/templates/etudiantManager/modifierCursusPostDUT.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Modification du cursus Post-DUT {{cursus}} de l'étudiant {{etudiant.nom}} {{etudiant.prenom}}</h1>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		
		<p><label for="annee">Année universitaire :</label> <select id="annee" name="annee" required>
			{% for annee in anneesUniversitaires %}
				<option value="{{annee}}">{{annee}}</option>
			{% endfor %}
		</select></p>
		
		{{ form.as_p }}
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/modifierCursusPreDUT.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Modification du cursus Pré-DUT {{cursus}} de l'étudiant {{etudiant.nom}} {{etudiant.prenom}}</h1>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		
		<p><label for="annee">Année universitaire :</label> <select id="annee" name="annee" required>
			{% for annee in anneesUniversitaires %}
				<option value="{{annee}}">{{annee}}</option>
			{% endfor %}
		</select></p>
		
		{{ form.as_p }}
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/modifierEtudiantInfoBAC.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Modification des informations concernant le BAC de l'etudiant {{ etudiant.nom }} {{ etudiant.prenom }}</h1>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		
		<p><label for="id_BAC">BAC :</label> <select id="id_BAC" name="BAC">
		
		<option value=""
		{% if etudiant.BAC == None %}
			 selected="selected"
		{% endif %}
		>---------</option>
		
		{% for BAC in BACs %}
			<option value="{{BAC.id}}"
			{% if etudiant.BAC == BAC %}
				 selected="selected"
			{% endif %}
			>{{BAC}}</option>
		{% endfor %}
		
		</select></p><!-- Fin select BAC -->
		
		<p><label for="id_mentionBAC">Mention du BAC :</label> <select id="id_mentionBAC" name="mentionBAC">
		
		<option value=""
		{% if etudiant.mentionBAC == None %}
			 selected="selected"
		{% endif %}
		>---------</option>
		
		{% for mention in mentions %}
			<option value="{{mention.id}}"
			{% if etudiant.mentionBAC == mention %}
				 selected="selected"
			{% endif %}
			>{{mention}}</option>
		{% endfor %}
		
		</select></p><!-- Fin select mention -->
		
		<p><label for="anneeBAC">Année du BAC :</label> <select id="anneeBAC" name="anneeBAC">
		
		<option value=""
		{% if etudiant.anneeBAC == None %}
			 selected="selected"
		{% endif %}
		>---------</option>
		
		{% for annee in anneesUniversitaires %}
			<option value="{{annee}}"
			{% if etudiant.anneeBAC.anneeUniversitaire == annee %}
				 selected="selected"
			{% endif %}
			>{{annee}}</option>
		{% endfor %}
		</select></p><!-- Fin select anneeBAC -->
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/modifierEtudiantInfoPerso.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>Modification des informations personnelles de l'etudiant {{ etudiant.nom }} {{ etudiant.prenom }}</h1>
	<form method='POST' action='#'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/modifierMoyenne.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	
	<h2>Moyennes du {{semestre}} de l'étudiant {{etudiant.nom}} {{etudiant.prenom}}</h2>
	
	<form method='POST' action='#'>
		{% csrf_token %}
		<table>
			<caption>{{tableau.ligneEntete}}</caption>
			{% for ligne in tableau.ligneTableau %}
				<tr>
					<td>{{ligne.0}}</td>
					<td><input type="number" name="{{ligne.2}}" step="0.001" value="{{ligne.1}}" required></td>
				</tr>
			{% endfor %}
		</table>
		
		<input type="submit" value="Valider">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
	</form>
	
{% endblock %}

etudiantManager/templates/etudiantManager/paramImportEtudiant.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h2>Importer des Etudiants</h2>
	
	<form action="importerEtudiant" method="POST">
		{% csrf_token %}
		<label>Semestre : </label>
		<select name="idSemestrePossible" required>
		{% for semestre in semestres %}
			<option value='{{semestre.id}}'>{{semestre.semestre}}</option>
		{% endfor %}
		</select><br>
		<br>
		<label>Année universitaire : </label><select name="anneeUniversitaire" required>
		{% for annee in anneesUniversitaires %}
			<option value='{{annee}}' {% if annee == anneeParDefaut %}selected{% endif %}>{{annee}}</option>
		{% endfor %}
		</select><br>
		<br>
		<label>Fichier CSV : </label><input type="file" accept=".csv" name="fichier" required><br><br>
		<input type="submit" value="Importer">
		<input type="reset" value="Annuler">
		<input type="button" value="Retour" onClick="history.go(-1);return true;">
		<p><strong>ATTENTION ! Lorsque vous cliquerez sur "importer" il est possible que le chargement de la page puisse prendre quelques minutes. Ne paniquez pas, et attendez patiemment la fin du chargement. Evitez de fermer votre navigateur durant le chargement ou de cliquer plusieurs fois sur "importer".</strong></p>
	</form>
{% endblock %}

etudiantManager/templates/etudiantManager/supprimerEtudiant.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1>L'etudiant {{ etudiant.nom }} {{ etudiant.prenom }} à bien été supprimé.</h1>
	<a href="/gestionEtudiant/listeEtudiant"><input type="button" value="Retour à la gestion des étudiants" /></a>
{% endblock %}